/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/': RouteRecordInfo<
      '/accumulations/',
      '/accumulations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/一剪梅': RouteRecordInfo<
      '/accumulations/一剪梅',
      '/accumulations/%E4%B8%80%E5%89%AA%E6%A2%85',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/临江仙_0': RouteRecordInfo<
      '/accumulations/临江仙_0',
      '/accumulations/%E4%B8%B4%E6%B1%9F%E4%BB%99_0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/冲雪宿新寨忽忽不乐': RouteRecordInfo<
      '/accumulations/冲雪宿新寨忽忽不乐',
      '/accumulations/%E5%86%B2%E9%9B%AA%E5%AE%BF%E6%96%B0%E5%AF%A8%E5%BF%BD%E5%BF%BD%E4%B8%8D%E4%B9%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/凉州词': RouteRecordInfo<
      '/accumulations/凉州词',
      '/accumulations/%E5%87%89%E5%B7%9E%E8%AF%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/别匡山': RouteRecordInfo<
      '/accumulations/别匡山',
      '/accumulations/%E5%88%AB%E5%8C%A1%E5%B1%B1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/念奴娇_过洞庭': RouteRecordInfo<
      '/accumulations/念奴娇_过洞庭',
      '/accumulations/%E5%BF%B5%E5%A5%B4%E5%A8%87_%E8%BF%87%E6%B4%9E%E5%BA%AD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/滕王阁序': RouteRecordInfo<
      '/accumulations/滕王阁序',
      '/accumulations/%E6%BB%95%E7%8E%8B%E9%98%81%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/琵琶行': RouteRecordInfo<
      '/accumulations/琵琶行',
      '/accumulations/%E7%90%B5%E7%90%B6%E8%A1%8C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/登泰山记': RouteRecordInfo<
      '/accumulations/登泰山记',
      '/accumulations/%E7%99%BB%E6%B3%B0%E5%B1%B1%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/相信': RouteRecordInfo<
      '/accumulations/相信',
      '/accumulations/%E7%9B%B8%E4%BF%A1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/记念刘和珍君': RouteRecordInfo<
      '/accumulations/记念刘和珍君',
      '/accumulations/%E8%AE%B0%E5%BF%B5%E5%88%98%E5%92%8C%E7%8F%8D%E5%90%9B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/送家静及第后赴官清水': RouteRecordInfo<
      '/accumulations/送家静及第后赴官清水',
      '/accumulations/%E9%80%81%E5%AE%B6%E9%9D%99%E5%8F%8A%E7%AC%AC%E5%90%8E%E8%B5%B4%E5%AE%98%E6%B8%85%E6%B0%B4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/酬乐天咏老见示': RouteRecordInfo<
      '/accumulations/酬乐天咏老见示',
      '/accumulations/%E9%85%AC%E4%B9%90%E5%A4%A9%E5%92%8F%E8%80%81%E8%A7%81%E7%A4%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/锦瑟': RouteRecordInfo<
      '/accumulations/锦瑟',
      '/accumulations/%E9%94%A6%E7%91%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/题龙阳县青草湖': RouteRecordInfo<
      '/accumulations/题龙阳县青草湖',
      '/accumulations/%E9%A2%98%E9%BE%99%E9%98%B3%E5%8E%BF%E9%9D%92%E8%8D%89%E6%B9%96',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accumulations/鹧鸪天_赏荷': RouteRecordInfo<
      '/accumulations/鹧鸪天_赏荷',
      '/accumulations/%E9%B9%A7%E9%B8%AA%E5%A4%A9_%E8%B5%8F%E8%8D%B7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fools/': RouteRecordInfo<
      '/fools/',
      '/fools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024AnnualSummary/': RouteRecordInfo<
      '/posts/2024AnnualSummary/',
      '/posts/2024AnnualSummary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025AnnualSummary/': RouteRecordInfo<
      '/posts/2025AnnualSummary/',
      '/posts/2025AnnualSummary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/AccumulationDev/': RouteRecordInfo<
      '/posts/AccumulationDev/',
      '/posts/AccumulationDev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Awesome/vol1/': RouteRecordInfo<
      '/posts/Awesome/vol1/',
      '/posts/Awesome/vol1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/csharp_typeof_gettype': RouteRecordInfo<
      '/posts/csharp_typeof_gettype',
      '/posts/csharp_typeof_gettype',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ECS-TH1/': RouteRecordInfo<
      '/posts/ECS-TH1/',
      '/posts/ECS-TH1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/EpicOfAtom/': RouteRecordInfo<
      '/posts/EpicOfAtom/',
      '/posts/EpicOfAtom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FeelingsViaMusic/': RouteRecordInfo<
      '/posts/FeelingsViaMusic/',
      '/posts/FeelingsViaMusic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GetRIME/': RouteRecordInfo<
      '/posts/GetRIME/',
      '/posts/GetRIME',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSChemOrganicBurnCompute/': RouteRecordInfo<
      '/posts/HSChemOrganicBurnCompute/',
      '/posts/HSChemOrganicBurnCompute',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSChemOrganicPhysicalAttributes/': RouteRecordInfo<
      '/posts/HSChemOrganicPhysicalAttributes/',
      '/posts/HSChemOrganicPhysicalAttributes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSChemOrganicReactionCondition/': RouteRecordInfo<
      '/posts/HSChemOrganicReactionCondition/',
      '/posts/HSChemOrganicReactionCondition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSChineseHetorical/': RouteRecordInfo<
      '/posts/HSChineseHetorical/',
      '/posts/HSChineseHetorical',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSEnglish3500/A': RouteRecordInfo<
      '/posts/HSEnglish3500/A',
      '/posts/HSEnglish3500/A',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSEnglish3500/B': RouteRecordInfo<
      '/posts/HSEnglish3500/B',
      '/posts/HSEnglish3500/B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSEnglish3500/tools': RouteRecordInfo<
      '/posts/HSEnglish3500/tools',
      '/posts/HSEnglish3500/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HSMathStatistic/': RouteRecordInfo<
      '/posts/HSMathStatistic/',
      '/posts/HSMathStatistic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LifeBegetsDeath/': RouteRecordInfo<
      '/posts/LifeBegetsDeath/',
      '/posts/LifeBegetsDeath',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MermaidBeginner/': RouteRecordInfo<
      '/posts/MermaidBeginner/',
      '/posts/MermaidBeginner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TailwindCSSBeginner/': RouteRecordInfo<
      '/posts/TailwindCSSBeginner/',
      '/posts/TailwindCSSBeginner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/YouthLivesForever/': RouteRecordInfo<
      '/posts/YouthLivesForever/',
      '/posts/YouthLivesForever',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.40_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parser@7.29.7_@nuxt+kit@3.21.9_magicast@0.5.3__@types+markdown-it_151885349cd2e0d071c618a48007a116/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/index.md': {
      routes:
        | '/accumulations/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/一剪梅.md': {
      routes:
        | '/accumulations/一剪梅'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/临江仙_0.md': {
      routes:
        | '/accumulations/临江仙_0'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/冲雪宿新寨忽忽不乐.md': {
      routes:
        | '/accumulations/冲雪宿新寨忽忽不乐'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/凉州词.md': {
      routes:
        | '/accumulations/凉州词'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/别匡山.md': {
      routes:
        | '/accumulations/别匡山'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/念奴娇_过洞庭.md': {
      routes:
        | '/accumulations/念奴娇_过洞庭'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/滕王阁序.md': {
      routes:
        | '/accumulations/滕王阁序'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/琵琶行.md': {
      routes:
        | '/accumulations/琵琶行'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/登泰山记.md': {
      routes:
        | '/accumulations/登泰山记'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/相信.md': {
      routes:
        | '/accumulations/相信'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/记念刘和珍君.md': {
      routes:
        | '/accumulations/记念刘和珍君'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/送家静及第后赴官清水.md': {
      routes:
        | '/accumulations/送家静及第后赴官清水'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/酬乐天咏老见示.md': {
      routes:
        | '/accumulations/酬乐天咏老见示'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/锦瑟.md': {
      routes:
        | '/accumulations/锦瑟'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/题龙阳县青草湖.md': {
      routes:
        | '/accumulations/题龙阳县青草湖'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/accumulations/鹧鸪天_赏荷.md': {
      routes:
        | '/accumulations/鹧鸪天_赏荷'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fools/index.md': {
      routes:
        | '/fools/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.40_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.40_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/2024AnnualSummary/index.md': {
      routes:
        | '/posts/2024AnnualSummary/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/2025AnnualSummary/index.md': {
      routes:
        | '/posts/2025AnnualSummary/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/AccumulationDev/index.md': {
      routes:
        | '/posts/AccumulationDev/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Awesome/vol1/index.md': {
      routes:
        | '/posts/Awesome/vol1/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/csharp_typeof_gettype.md': {
      routes:
        | '/posts/csharp_typeof_gettype'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ECS-TH1/index.md': {
      routes:
        | '/posts/ECS-TH1/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/EpicOfAtom/index.md': {
      routes:
        | '/posts/EpicOfAtom/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/FeelingsViaMusic/index.md': {
      routes:
        | '/posts/FeelingsViaMusic/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GetRIME/index.md': {
      routes:
        | '/posts/GetRIME/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSChemOrganicBurnCompute/index.md': {
      routes:
        | '/posts/HSChemOrganicBurnCompute/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSChemOrganicPhysicalAttributes/index.md': {
      routes:
        | '/posts/HSChemOrganicPhysicalAttributes/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSChemOrganicReactionCondition/index.md': {
      routes:
        | '/posts/HSChemOrganicReactionCondition/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSChineseHetorical/index.md': {
      routes:
        | '/posts/HSChineseHetorical/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSEnglish3500/A.md': {
      routes:
        | '/posts/HSEnglish3500/A'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSEnglish3500/B.md': {
      routes:
        | '/posts/HSEnglish3500/B'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSEnglish3500/tools.md': {
      routes:
        | '/posts/HSEnglish3500/tools'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HSMathStatistic/index.md': {
      routes:
        | '/posts/HSMathStatistic/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/LifeBegetsDeath/index.md': {
      routes:
        | '/posts/LifeBegetsDeath/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MermaidBeginner/index.md': {
      routes:
        | '/posts/MermaidBeginner/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/TailwindCSSBeginner/index.md': {
      routes:
        | '/posts/TailwindCSSBeginner/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/YouthLivesForever/index.md': {
      routes:
        | '/posts/YouthLivesForever/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
