/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/accumulations/': RouteRecordInfo<'/accumulations/', '/accumulations', Record<never, never>, Record<never, never>>,
    '/accumulations/酬乐天咏老见示': RouteRecordInfo<'/accumulations/酬乐天咏老见示', '/accumulations/酬乐天咏老见示', Record<never, never>, Record<never, never>>,
    '/accumulations/锦瑟': RouteRecordInfo<'/accumulations/锦瑟', '/accumulations/锦瑟', Record<never, never>, Record<never, never>>,
    '/accumulations/凉州词': RouteRecordInfo<'/accumulations/凉州词', '/accumulations/凉州词', Record<never, never>, Record<never, never>>,
    '/accumulations/念奴娇_过洞庭': RouteRecordInfo<'/accumulations/念奴娇_过洞庭', '/accumulations/念奴娇_过洞庭', Record<never, never>, Record<never, never>>,
    '/accumulations/琵琶行': RouteRecordInfo<'/accumulations/琵琶行', '/accumulations/琵琶行', Record<never, never>, Record<never, never>>,
    '/accumulations/滕王阁序': RouteRecordInfo<'/accumulations/滕王阁序', '/accumulations/滕王阁序', Record<never, never>, Record<never, never>>,
    '/accumulations/题龙阳县青草湖': RouteRecordInfo<'/accumulations/题龙阳县青草湖', '/accumulations/题龙阳县青草湖', Record<never, never>, Record<never, never>>,
    '/accumulations/相信': RouteRecordInfo<'/accumulations/相信', '/accumulations/相信', Record<never, never>, Record<never, never>>,
    '/accumulations/一剪梅': RouteRecordInfo<'/accumulations/一剪梅', '/accumulations/一剪梅', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/fools/': RouteRecordInfo<'/fools/', '/fools', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024年末总结/': RouteRecordInfo<'/posts/2024年末总结/', '/posts/2024年末总结', Record<never, never>, Record<never, never>>,
    '/posts/听曲偶感/': RouteRecordInfo<'/posts/听曲偶感/', '/posts/听曲偶感', Record<never, never>, Record<never, never>>,
    '/posts/csharp_typeof_gettype': RouteRecordInfo<'/posts/csharp_typeof_gettype', '/posts/csharp_typeof_gettype', Record<never, never>, Record<never, never>>,
    '/posts/ECS-TH1初识/': RouteRecordInfo<'/posts/ECS-TH1初识/', '/posts/ECS-TH1初识', Record<never, never>, Record<never, never>>,
    '/posts/Mermaid简明指南/': RouteRecordInfo<'/posts/Mermaid简明指南/', '/posts/Mermaid简明指南', Record<never, never>, Record<never, never>>,
    '/posts/TailwindCSS入门小记/': RouteRecordInfo<'/posts/TailwindCSS入门小记/', '/posts/TailwindCSS入门小记', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
